### ISSUE TITLE
SC Mixed RC

### ISSUE THREAD

**Issue by Acobut** [HPDCollaborative/special-conditions-beta#1]
Hello,
I've been testing the Builder with the special conditions features. I found that the disclaimer required from the PDF "This disclosure does not provide information on the potential presence of hazardous substances which may be found in certain mixed recycled materials." was missing in the Builder.

**Comment by 19peaches** [comment]
This disclaimer if only required if "no information" is available on hazards. Let me get some clarification on what "no information" means exactly.

**Comment by 19peaches** [comment]
@Acobut 

I'm still waiting on official word for this, but initially I've pushed a fix that includes the disclaimer when:

1. Testing is no
2. Testing is yes AND the testing text block is empty

This may change if the definition of "no information" is tighter or looser than what @JEGeyer and I talked through to get this started.

**Comment by JEGeyer** [comment]
Here's the response I got from Tristan, when asking him for clarification on the SC Guidance:

"Checked with Joel…. we think the disclaimer should default to appearing on ALL substances using this SC.
The only case I see where I think it would be appropriate to remove the disclaimer is if this question is answered yes, and information is provided in response to the following: 
  If “yes”, include the following information:

- list of chemicals and/or elements (including those of a hazardous nature) that are covered by the testing;
- test method(s) employed;
- name and accreditation of the lab(s) that perform the testing;
- representative material sample covered by the testing.

Is this workable? Looks to me like the SC guidance should be clarified a bit."_

**Since we can't programmatically check how well the bulleted information is addressed, I suggest that we follow Tristan's first recommendation and include the disclaimer for all substances using this SC.**

**Comment by 19peaches** [comment]
This has been implemented in the builder.
