### ISSUE TITLE
HPD completion checks

### ISSUE THREAD

**Issue by Acobut** [HPDCollaborative/special-conditions-beta#5]
Hello,

When you generate the completion check, there are multiple notifications regarding the notes (material/substance). Even though those notes are generated automatically for special conditions, it will be notified during checks. So I don't know, if you could review the check screening and adapt it for automated notes in the context of special conditions.

**Comment by 19peaches** [comment]
No this isn't possible as the SC information is rendered only when generating a PDF document either for preview or publishing. Not to mention that anything auto-rendered wouldn't be able to be addressed by the user anyway since they have no control over when and how those notes are rendered. The Completion Check already checks to ensure that required SC parameters are met.  If you run the check with an SC material and no SC substance attached you'll see this in action.
